### ISSUE TITLE
add spring security principal

### ISSUE THREAD

**Issue by tedder** [antonmos/one-line-access-log#2]
Hi- if the spring-security-core principal (username) was added, I'd love that.

If you can point me to where that should be added I am willing to fuss around and see if I can add it.

**Comment by antonmos** [comment]
In order to keep the plugin simple, i did not want to couple it with spring-security. Another words, apps that dont use spring-security should not be forced to pull in that dependency.

I think you should be able to do what you need with another filter that will put the username into Log4j's MDC and configuring log4j logger format to print it. see this [section in the readme](https://github.com/antonmos/one-line-access-log#configuration-of-application-specific-grails-filters) to see how to configure this. 

Let me know if this works for you! Thanks

**Comment by tedder** [comment]
thanks! I'll dig and report back, but it'll take me a few days. Closing 'til then.
